typedef union {
	int i;
	unsigned int ui;
	float f;
	const void *v;
} Arg;
static void tile(Monitor *m);
static void monocle(Monitor *m);
static void focusmon(Arg *arg);
static void focusstack(Arg *arg);
static void incnmaster(Arg *arg);
static void killclient(Arg *arg);
static void movemouse(Arg *arg);
static void quit(Arg *arg);
static void refreshconfig(Arg *arg);
static void resizemouse(Arg *arg);
static void setlayout(Arg *arg);
static void setmfact(Arg *arg);
static void spawn(Arg *arg);
static void tag(Arg *arg);
static void tagmon(Arg *arg);
static void togglebar(Arg *arg);
static void togglefloating(Arg *arg);
static void toggletag(Arg *arg);
static void toggleview(Arg *arg);
static void view(Arg *arg);
static void zoom(Arg *arg);