typedef union {
	int i;
	unsigned int ui;
	float f;
	const void *v;
} Arg;
static void tile(Monitor *m);
static void monocle(Monitor *m);
static void focusmon(const Arg *arg);
static void focusstack(const Arg *arg);
static void incnmaster(const Arg *arg);
static void killclient(const Arg *arg);
static void movemouse(const Arg *arg);
static void quit(const Arg *arg);
static void refreshconfig(const Arg *arg);
static void resizemouse(const Arg *arg);
static void setlayout(const Arg *arg);
static void setmfact(const Arg *arg);
static void spawn(const Arg *arg);
static void tag(const Arg *arg);
static void tagmon(const Arg *arg);
static void togglebar(const Arg *arg);
static void togglefloating(const Arg *arg);
static void toggletag(const Arg *arg);
static void toggleview(const Arg *arg);
static void view(const Arg *arg);
static void zoom(const Arg *arg);